name: Rezilion Test GitHub Action
on: [push]
jobs:
  rezilion-scan:
    runs-on: ubuntu-latest
    container:
      image: redis:7.0.4
    env:
     REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
     REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.9.0
        with:
          image_name: 'redis:7.0.4'
          mode: 'start'
          
          command: |
            timeout 10 redis-server || true
  

  rezilion-validate:
    needs: [rezilion-test-runtimes]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:b63c85d0

    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.9.0
        with:
          mode: 'validate'
